Adds prettier

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -38,6 +38,21 @@ pipeline {
 				}
 			}
 		}
+		stage('Format Service') {
+			steps {
+				nvm(readFile(".nvmrc").trim()) {
+					sh '''
+					npm run format
+					if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
+						echo "All files formatted"
+					else
+						echo "Running format is required"
+						exit 1
+					fi
+					'''
+				}
+			}
+		}
 		stage('Perform unit tests') {
 			steps {
 				script { echoBanner(STAGE_NAME) }
